name: Build WASM PGlite files

on:
  workflow_call:

jobs:
  build:
    name: Build WASM Postgres
    runs-on: ubuntu-22.04
    env:
      PGVERSION: 16.4
      SDK_VERSION: 3.1.65.8bi
      SDK_ARCHIVE: python3.12-wasm-sdk-Ubuntu-22.04.tar.lz4
      SDKROOT: /opt/python-wasm-sdk
      SYS_PYTHON: /usr/bin/python3
      PGROOT: /tmp/pglite
      DEBUG: true
      WASI: false
      PGES6: true
      contrib: contrib
      OBJDUMP: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore cached build
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: |
            /opt/python-wasm-sdk
            /tmp/web
            /tmp/pglite
            /tmp/sdk/postgres-*.tar.gz
            postgres
            postgresql-*
          key: build-cache-${{ hashFiles('cibuild/**', 'patches/*.c', 'patches/postgresql-*') }}

      - name: Install python-wasm-sdk for emsdk/wasi+prebuilts
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: /
        run: |
          sudo apt-get install -y lz4 wget pv bash
          echo https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE
          curl -sL --retry 5 https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE | tar xvP --use-compress-program=lz4 | pv -p -l -s 24400 >/dev/null

      - name: Build postgres WASM via emsdk
        run: |
          bash ./cibuild.sh vector contrib node linkweb pglite pglite-prep


      - name: Build REPL for Example deployment
        working-directory: ./packages/repl
        run: |
          pnpm install
          pnpm run build

      - name : "Upload to GitHub pages"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: /tmp/web

      - name: Test pglite
        working-directory: ./packages/pglite
        run: |
          pnpm exec playwright install --with-deps
          pnpm run test
